config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'home#welcome'

  resources :riders do
	resources :hobbies  
end


  resources :places
  resources :rides

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/place.rb
class Place < ApplicationRecord

	DEAFULT_PLACE = "UDUPI"

	default_scope { where(:place_type => "") }

	scope :welcome, -> { where(:lat => "testdsfgsdfgsdfg" )}

	include PlaceRefo

	def test_pro
		test_one
	end

  private

  def self.my_method
    puts "regular method"
  end

end

app/models/ride.rb
class Ride < ApplicationRecord
	serialize :riders_list
	serialize :locations_list
	has_many :rides
	has_many :places 
end

app/models/rider.rb
class Rider < ApplicationRecord
  has_secure_password
  
  validates_presence_of :email, :password, :name, :city, :bike, :age 
  validates :password, length: { minimum: 6 }

  scope :age, -> { where(created_at: 'desc') }


  def as_json
  	super(only: [:email, :name, :city, :bike, :age])
  end

  def print_name
	"MY NAME"
  end
  
end

app/models/slave.rb
class Slave < ApplicationRecord
end

app/models/test_person.rb
class TestPerson < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= session[:rider_id] &&
      Rider.find_by(id: session[:rider_id])
  end

end

app/controllers/concerns/place_refo.rb
module PlaceRefo
	extend ActiveSupport::Concern
	included do 
		def test_one
			puts "TEST"
		end
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def welcome
		@show_search_form = true
		search_query = nil
		search_query = params[:search_query]
		@riders = []
    	@riders = Rider.where("name LIKE ?" ,"%#{search_query}%") unless search_query.blank?
    	@user_search = true unless search_query.blank?
	end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController

  before_action :set_place, only: [:show, :edit, :update, :destroy]

  def index
    @place = Place.new
    @places = Place.all
    @hash = Gmaps4rails.build_markers(@places) do |place, marker|
      marker.lat place.lat
      marker.lng place.lng
    end
  end

 
  def show
  end

 
  def new
    @place = Place.new
  end

 
  def edit
  end


  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

 
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

 
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:place_name, :place_type, :lat, :lng, :state)
    end
end

app/controllers/riders_controller.rb
class RidersController < ApplicationController
  before_action :set_rider, only: [:show, :edit, :update, :destroy]

  def index
    @riders = Rider.all
    @rider = Rider.new
  end


  def show
  end

 
  def new
    @rider = Rider.new
  end

 
  def edit
  end

 
  def create
    @rider = Rider.new(rider_params)

    respond_to do |format|
      if @rider.save
        format.html { redirect_to @rider, notice: 'Rider was successfully created.' }
        format.json { render :show, status: :created, location: @rider }
      else
        @error_on_register = true
        format.html { render :index }
        format.json { render json: @rider.errors, status: :unprocessable_entity }
      end
    end
  end

 
  def update
    respond_to do |format|
      if @rider.update(rider_params)
        format.html { redirect_to @rider, notice: 'Rider was successfully updated.' }
        format.json { render :show, status: :ok, location: @rider }
      else
        format.html { render :edit }
        format.json { render json: @rider.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def destroy
    @rider.destroy
    respond_to do |format|
      format.html { redirect_to riders_url, notice: 'Rider was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rider
      @rider = current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rider_params
      params.require(:rider).permit(:email, :password, :password_confirmation, :name, :city, :bike, :age)
    end
end

app/controllers/rides_controller.rb
class RidesController < ApplicationController

	def index
	
	end


	def new
	
	end


	def show
	
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    rider = Rider.find_by_email(params[:email])
    if rider && rider.authenticate(params[:password])
      session[:rider_id] = rider.id
      flash[:notice] = "Success"
      redirect_to '/'
    else
      redirect_to '/login'
    end
  end

  def destroy
  	reset_session
  	redirect_to '/login'
  end

end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def present(object, klass =nil)
		klass ||= "#{object.class}Presenter".constantize
		presenter = klass.new(object, self)
		yield presenter if block_givern?
		presenter
	end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/riders_helper.rb
module RidersHelper
end

app/helpers/rides_helper.rb
module RidesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/places/_form.html.erb
<div class="modal fade" id="new_place_registration_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Place registration</h4>
      </div>
      <div class="modal-body" id="place_registration_form_container">
        <%= form_for(place) do |f| %>
        <% if place.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(place.errors.count, "error") %> prohibited this place from being saved:</h2>
          <ul>
            <% place.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        </div>
        <% end %>
        
        <div class="form-group">
          <%= f.label :place_name, class: "control-label" %>
          <%= f.text_field :place_name, class: "form-control", maxlength: "50" %>
        </div>
        <div class="form-group">
          <%= f.label :type, class: "control-label" %>
          <%= f.text_field :place_type, class: "form-control", maxlength: "50" %>
        </div>
        <div class="form-group">
          <%= f.label :Latitude, class: "control-label" %>
          <%= f.text_field :lat, class: "form-control", maxlength: "50" %>
        </div>
        
        <div class="latlng-selector" data-toggle="modal" data-target="#latlng_modal" onclick="initialize_map()"> Choose from Map </div>
        <div class="modal fade" id="latlng_modal" role="dialog">
          <div class="modal-dialog" id="map_modal_div">
            <div class="modal-content">
              <div class="modal-header">
                 <button type="button" class="close" aria-label="Close" id="latlng_modal_close_btn" onclick="close_latlng_selector()" ><span aria-hidden="true">&times;</span></button>
              </div>
              <div class="modal-body">
                <div id="map-canvas" class=""></div>
              </div>
            </div>
          </div>
        </div>
        
        <div class="form-group">
          <%= f.label :Longitude, class: "control-label" %>
          <%= f.text_field :lng, class: "form-control", maxlength: "50" %>
        </div>
        <div class="form-group">
          <%= f.label :state, class: "control-label" %>
          <%= f.text_field :state, class: "form-control", maxlength: "50" %>
        </div>
        <div class="form-group">
          <%= f.submit 'Register', :class => "btn btn-info btn-block" %>
        </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>


<%= javascript_include_tag 'places' %>
 

app/views/places/edit.html.erb
<h1>Editing Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <table id="places_table" class="table table-striped table-bordered" cellspacing="0" width="100%">
    <thead>
      <div id="custom_places_filter_container">
        Search : <input type="text" id="searchbox">
      </div>
      <tr>
        <th>Place name</th>
        <th>Type</th>
        <th>Lat</th>
        <th>Lng</th>
        <th>State</th>
      </tr>
    </thead>
    <tbody>
      <% @places.each do |place| %>
      <tr>
        <td><%= place.place_name %></td>
        <td><%= place.place_type %></td>
        <td><%= place.lat %></td>
        <td><%= place.lng %></td>
        <td><%= place.state %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  
  <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#new_place_registration_modal">
  Add Place
  </button>
</div>

 
<%= render 'form', place: @place %>


<script type="text/javascript">
    $('#places_table').DataTable({
        paging: false
    });

    $(document).ready(function() {
        var dataTable = $('#places_table').dataTable();
        $("#searchbox").keyup(function() {
            dataTable.fnFilter(this.value);
        });
    });
</script>



 
 

app/views/places/new.html.erb
<h1>New Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Place name:</strong>
  <%= @place.place_name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @place.place_type %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @place.lat %>
</p>

<p>
  <strong>Lng:</strong>
  <%= @place.lng %>
</p>

<p>
  <strong>State:</strong>
  <%= @place.state %>
</p>

<%= link_to 'Edit', edit_place_path(@place) %> |
<%= link_to 'Back', places_path %>

app/views/riders/_form.html.erb
<div class="modal fade" id="new_rider_registration_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Rider registration</h4>
      </div>
      <div class="modal-body" id="rider_registration_form_container">
        <%= form_for(rider) do |f| %>
        <% if rider.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(rider.errors.count, "error") %> prohibited this rider from being saved:</h2>
          <ul>
            <% rider.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        </div>
        <% end %>
        <div class="form-group">
          <%= f.label :email, class: "control-label"%>
          <%= f.text_field :email, value: nil, class: "form-control", maxlength: "50",:autocomplete => :off %>
        </div>
        <div class="form-group">
          <%= f.label :password, class: "control-label"%>
          <%= f.password_field :password, value: nil, class: "form-control", maxlength: "50",:autocomplete => :off %>
        </div>
        
        <div class="form-group">
          <%= f.label :name, class: "control-label"%>
          <%= f.text_field :name, class: "form-control", maxlength: "50" %>
        </div> 
        <div class="form-group">
          <%= f.label :city, class: "control-label" %>
          <%= f.text_field :city, class: "form-control", maxlength: "50"  %>
        </div>
        <div class="form-group">
          <%= f.label :bike, class: "control-label" %>
          <%= f.text_field :bike, class: "form-control", maxlength: "50"  %>
        </div>
        <div class="form-group">
          <%= f.label :age, class: "control-label" %>
          <%= f.number_field :age, class: "form-control", maxlength: "2", within: 20...50 %>
        </div>
        <div class="form-group">
          <%= f.submit 'Register', :class => "btn btn-info btn-block" %>
        </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <p>By creating an account, you agree to our <a href="#">Terms of Use</a> and our <a href="#">Privacy Policy</a>.</p>
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/riders/_riders_search_result.html.erb
<% if @riders.blank? %>
No records to show.
<% else %>
<table id="riders_table" class="table table-striped table-bordered" cellspacing="0" width="100%">
  <thead>
    <div id="custom_riders_filter_container">
      Search : <input type="text" id="searchbox">
    </div>
    <tr>
      <th>Name</th>
      <th>City</th>
      <th>Bike</th>
      <th>Age</th>
    </tr>
  </thead>
  <tbody>
    <% @riders.each do |rider| %>
    <tr>
      <td><%= rider.name %></td>
      <td><%= rider.city %></td>
      <td><%= rider.bike %></td>
      <td>
        <% present rider do  |rider_presenter|%>
        <%= rider_presenter.age %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/riders/edit.html.erb
<h1>Editing Rider</h1>

<%= render 'form', rider: @rider %>

<%= link_to 'Show', @rider %> |
<%= link_to 'Back', riders_path %>

app/views/riders/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
    <%= render "riders_search_result" %>
  <br>
  <br>
  <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#new_rider_registration_modal">
  Register
  </button>
</div>

<script type="text/javascript">
  $('#riders_table').DataTable({
      paging: false 
      }
    );
 
$(document).ready(function() {
  var dataTable = $('#riders_table').dataTable();
    $("#searchbox").keyup(function() {
        dataTable.fnFilter(this.value);
    });   
} );
</script>



<%= render 'form', rider: @rider %>


<% if @error_on_register %>
<script type="text/javascript">
  $("#new_rider_registration_modal").modal('show');
</script>
<% end%> 

app/views/riders/new.html.erb
<h1>New Rider</h1>

<%= render 'form', rider: @rider %>

<%= link_to 'Back', riders_path %>

app/views/riders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @rider.name %>
</p>

<p>
  <strong>City:</strong>
  <%= @rider.city %>
</p>

<p>
  <strong>Bike:</strong>
  <%= @rider.bike %>
</p>

<p>
  <strong>Age:</strong>
  <%= @rider.age %>
</p>

<%= link_to 'Edit', edit_rider_path(@rider) %> |
<%= link_to 'Back', riders_path %>